// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPZeCfSYmRXwtg1HC_HPCEIkxajZ8cdvw',
    appId: '1:863335258309:web:a1d365b5eb7549a0f5f8ac',
    messagingSenderId: '863335258309',
    projectId: 'chatchat-1b9c4',
    authDomain: 'chatchat-1b9c4.firebaseapp.com',
    storageBucket: 'chatchat-1b9c4.appspot.com',
    measurementId: 'G-S5HZLL1MQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbkgKNp2Vbc-ve6KRH4TiIrTlAH6d-kbo',
    appId: '1:863335258309:android:e1bd5f8cc2235be2f5f8ac',
    messagingSenderId: '863335258309',
    projectId: 'chatchat-1b9c4',
    storageBucket: 'chatchat-1b9c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVjyyIgTSjlrLL2Q1MhDnWVIcZu67UbC4',
    appId: '1:863335258309:ios:3578776f19faf4d7f5f8ac',
    messagingSenderId: '863335258309',
    projectId: 'chatchat-1b9c4',
    storageBucket: 'chatchat-1b9c4.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVjyyIgTSjlrLL2Q1MhDnWVIcZu67UbC4',
    appId: '1:863335258309:ios:89365bff980d7ccef5f8ac',
    messagingSenderId: '863335258309',
    projectId: 'chatchat-1b9c4',
    storageBucket: 'chatchat-1b9c4.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
